version: "2"
services:
  nginx:
    image: ./nginx
    container_name: webapp-nginx
    ports:
    - 8080:80
    networks:
      bridge:
        - nginx
  httpd:
    image: ./httpd
    container_name: webapp-httpd
    ports:
    - 9090:80
    networks:
      bridge:
        - httpd