version: "3"
services:
  nginx:
    build: ./nginx
    container_name: webapp-nginx
    volumes:
    - ./html:/var/www/html/
    ports:
    - "8080:80"
  httpd:
    build: ./httpd
    container_name: webapp-httpd
    volumes:
    - ./html:/var/www/html/
    ports:
    - "9090:80"
