version: "3"
services:
  nginx:
    image: localhost:5000/web-nginx:latest
    container_name: web-nginx
    volumes:
    - ./html:/usr/share/nginx/html
    ports:
    - "8080:80"
    networks:
      - nginx
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  apache:
    image: localhost:5000/web-apache:latest
    container_name: web-apache
    volumes:
    - ./html:/var/www/html/
    ports:
    - "8081:80"
    networks:
      - apache
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

networks:
  nginx:
    driver: bridge
  apache:
    driver: bridge