version: "3"
services:
  nginx:
    build: ./nginx
    container_name: webapp-nginx
    volumes:
    - ./html:/usr/share/nginx/html
    ports:
    - "8080:80"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
  httpd:
    build: ./httpd
    container_name: webapp-httpd
    volumes:
    - ./html:/var/www/html/
    ports:
    - "9090:80"
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
